### PR TITLE
Update formatting for Solution to part 2 in episode 12

### PR DESCRIPTION
**Pull request by amanmdesai**
The present format is not reader friendly 
I have modified the formatting

### CODE REVIEW

**Comment by amanmdesai** [comment]
I dont know why the checks were not successful. 
I was able to deploy the webpage [Link](https://hsf-training.github.io/hsf-training-ml-webpage/12-Experimental_Data/index.html) -- see Solution to Part 2

**Comment by klieret** [comment]
Hi @amanmdesai thanks a lot for this! :)

The failing pre-commit check is unrelated to you, I'll fix that later.

**Comment by amanmdesai** [comment]
Thanks @klieret.

**Comment by klieret** [comment]
Ah btw, regarding the formatting: These extra commas are intended: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html

**Pull request merged**
